links:
  - name: "Regexp 101"
    link: "https://regex101.com/"
    icon: "ladybug"
    desc: "在线正则表达式"
  - name: "JSON2Go"
    link: "https://mholt.github.io/json-to-go/"
    icon: "google"
    desc: "快速生成结构体"
  - name: "Outline"
    link: "https://outline.lab.com"
    icon: "evernote"
    desc: "快速记录"
  - name: "任务看板"
    icon: "alphaBBoxOutline"
    link: "https://board.lab.com/"
  - name: "个人知识库"
    link: "https://wiki.lab.com"
    icon: "wikipedia"
    desc: "结构化整理"
  - name: "DSU"
    link: "https://dsu.lab.com"
    icon: "toggleSwitchOffOutline"
    desc: "结构化整理"
  - name: "Gitea"
    link: "https://gitea.lab.com"
    icon: "git"
  - name: "网页存档"
    link: "https://archive.lab.com"
    icon: "archive"
  - name: "Carbon"
    link: "https://carbon.lab.com"
    icon: "GamepadVariant"
  - name: "云产品倒计时"
    link: "https://cd.lab.com"
    icon: "update"
  - name: "设备: 主路由器"
    link: "https://router.lab.com"
    icon: "RouterNetwork"
  - name: "设备: 群晖 DS918"
    link: "https://nas.lab.com"
    icon: "nas"
  - name: "设备: 光猫"
    link: "https://cat.lab.com"
    icon: "cat"
  - name: "设备: 主交换机"
    link: "https://switch.lab.com"
    icon: "switch"
  - name: "设备: NUC8"
    link: "https://nuc.lab.com"
    icon: "console"
  - name: "设备: ThinkPad14"
    link: "https://tp14.lab.com"
    icon: "console"
  - name: "设备: ThinkBook15"
    link: "https://tp15.lab.com"
    icon: "console"
  - name: "设备: Wi-Fi6 AP"
    link: "https://wifi.lab.com"
    icon: "routerWireless"
