categories:
  - id: 1
    title: 社交媒体
  - id: 2
    title: 参考资料
  - id: 3
    title: 在线工具
  - id: "string-name"
    title: 新分类
  - id: "category-name"
    title: 新分类

links:
  - name: 微博
    link: "https://weibo.com"
    category: 1

  - name: "网易云音乐"
    link: "https://music.163.com/"
    category: 1

  - name: "知乎"
    link: "https://zhihu.com"
    category: 2

  - name: "掘金"
    link: "https://juejin.cn/"
    category: 2
